spring:
  application:
    name: order-service
  config:
    import: configserver:http://localhost:8083/config-server/
  cloud:
    config:
      profile: local # Profile to fetch from config server
      name: order-service # Application name (should match the config file prefix)
      label: master # Git branch to use
      fail-fast: true # Fail if config server is not available
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1

server:
  address: localhost
  port: 8084
  servlet:
    context-path: /order-service